/**
 * Prospect companies discovered by the outreach pipeline.
 *
 * GENERATED from the live database — regenerate with tools/genSwissOutreach.js rather
 * than hand-editing. Every company here is **invented**: the live rows were real Swiss
 * register entries, so names, UIDs and register URLs were replaced while the pipeline
 * shape (scores, reasons, statuses, campaign linkage) was kept.
 */
import type {ProspectCompanySeedRow} from "./types";

export const prospectCompaniesSeed: readonly ProspectCompanySeedRow[] = [
    {
        "id": "6a604cb4b57d7c4ac8a79c14",
        "campaign": "6a604ae47e5c12f7ab9d86cc",
        "companyName": "Basel Elektro AG",
        "uid": "CHE-100.200.300",
        "dedupeKey": "CHE-100.200.300",
        "canton": "BS",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200300",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Basel Elektro AG (AG) based in BS appears to offer general services.",
        "services": [],
        "score": 45,
        "scoreReason": "canton match (BS); relevant services (Elektro)",
        "status": "scored"
    },
    {
        "id": "6a604cb4b57d7c4ac8a79c15",
        "campaign": "6a604ae47e5c12f7ab9d86cc",
        "companyName": "Helvetic Plumbing Solutions SA",
        "uid": "CHE-100.200.302",
        "dedupeKey": "CHE-100.200.302",
        "canton": "BS",
        "legalForm": "SA",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200302",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Helvetic Plumbing Solutions SA (SA) based in BS appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (BS)",
        "status": "scored"
    },
    {
        "id": "6a604cb4b57d7c4ac8a79c16",
        "campaign": "6a604ae47e5c12f7ab9d86cc",
        "companyName": "Nordwest Elektrik AG",
        "uid": "CHE-100.200.303",
        "dedupeKey": "CHE-100.200.303",
        "canton": "BL",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200303",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Nordwest Elektrik AG (AG) based in BL appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (BL)",
        "status": "scored"
    },
    {
        "id": "6a604e8cb57d7c4ac8a79c1a",
        "campaign": "6a604d7d31c32b576e5bb709",
        "companyName": "Basel Elektro AG",
        "uid": "CHE-100.200.300",
        "dedupeKey": "CHE-100.200.300",
        "canton": "BS",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200300",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Basel Elektro AG (AG) based in BS appears to offer general services.",
        "services": [],
        "score": 45,
        "scoreReason": "canton match (BS); relevant services (Elektro)",
        "status": "scored"
    },
    {
        "id": "6a604e8cb57d7c4ac8a79c1b",
        "campaign": "6a604d7d31c32b576e5bb709",
        "companyName": "Helvetic Plumbing Solutions SA",
        "uid": "CHE-100.200.302",
        "dedupeKey": "CHE-100.200.302",
        "canton": "BS",
        "legalForm": "SA",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200302",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Helvetic Plumbing Solutions SA (SA) based in BS appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (BS)",
        "status": "scored"
    },
    {
        "id": "6a604e8cb57d7c4ac8a79c1c",
        "campaign": "6a604d7d31c32b576e5bb709",
        "companyName": "Nordwest Elektrik AG",
        "uid": "CHE-100.200.303",
        "dedupeKey": "CHE-100.200.303",
        "canton": "BL",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200303",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Nordwest Elektrik AG (AG) based in BL appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (BL)",
        "status": "scored"
    },
    {
        "id": "6a604e8cb57d7c4ac8a79c1d",
        "campaign": "6a604d7d31c32b576e5bb709",
        "companyName": "Jura Licht & Power AG",
        "uid": "CHE-100.200.304",
        "dedupeKey": "CHE-100.200.304",
        "canton": "BL",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200304",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Jura Licht & Power AG (AG) based in BL appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (BL)",
        "status": "scored"
    },
    {
        "id": "6a604e8cb57d7c4ac8a79c1e",
        "campaign": "6a604d7d31c32b576e5bb709",
        "companyName": "Birsfelden Building Services GmbH",
        "uid": "CHE-100.200.305",
        "dedupeKey": "CHE-100.200.305",
        "canton": "BL",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200305",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Birsfelden Building Services GmbH (GmbH) based in BL appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (BL)",
        "status": "scored"
    },
    {
        "id": "6a604e8cb57d7c4ac8a79c1f",
        "campaign": "6a604d7d31c32b576e5bb709",
        "companyName": "Dreiländereck Haustechnik AG",
        "uid": "CHE-100.200.306",
        "dedupeKey": "CHE-100.200.306",
        "canton": "BS",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200306",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Dreiländereck Haustechnik AG (AG) based in BS appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (BS)",
        "status": "scored"
    },
    {
        "id": "6a604e8cb57d7c4ac8a79c20",
        "campaign": "6a604d7d31c32b576e5bb709",
        "companyName": "Aargau TechInstall GmbH",
        "uid": "CHE-100.200.317",
        "dedupeKey": "CHE-100.200.317",
        "canton": "AG",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200317",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Aargau TechInstall GmbH (GmbH) based in AG appears to offer general services.",
        "services": [],
        "score": 40,
        "scoreReason": "canton match (AG)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c28",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Alpina Flooring (Schweiz) AG",
        "uid": "CHE-100.200.401",
        "dedupeKey": "CHE-100.200.401",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200401",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Alpina Flooring (Schweiz) AG (AG) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c29",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Belvedere AG Flooring",
        "uid": "CHE-100.200.402",
        "dedupeKey": "CHE-100.200.402",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200402",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Belvedere AG Flooring (AG) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c2a",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Seeland Flooring AG",
        "uid": "CHE-100.200.403",
        "dedupeKey": "CHE-100.200.403",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200403",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Seeland Flooring AG (AG) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c2b",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "HL Flooring Consult Sàrl en liquidation",
        "uid": "CHE-100.200.404",
        "dedupeKey": "CHE-100.200.404",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200404",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "HL Flooring Consult Sàrl en liquidation (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c2c",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Kämpf-Flooring GmbH",
        "uid": "CHE-100.200.405",
        "dedupeKey": "CHE-100.200.405",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200405",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Kämpf-Flooring GmbH (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c2d",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "NR Flooring Systems GmbH",
        "uid": "CHE-100.200.406",
        "dedupeKey": "CHE-100.200.406",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200406",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "NR Flooring Systems GmbH (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c2e",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Oberland Flooring GmbH in Liquidation",
        "uid": "CHE-100.200.407",
        "dedupeKey": "CHE-100.200.407",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200407",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Oberland Flooring GmbH in Liquidation (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c2f",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Marko Petrovic - Nano Alpine Flooring",
        "uid": "CHE-100.200.408",
        "dedupeKey": "CHE-100.200.408",
        "legalForm": "Einzelunternehmen",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200408",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Marko Petrovic - Nano Alpine Flooring (Einzelunternehmen) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c30",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "RTC Flooring Products CH GmbH in Liquidation",
        "uid": "CHE-100.200.409",
        "dedupeKey": "CHE-100.200.409",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200409",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "RTC Flooring Products CH GmbH in Liquidation (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c31",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Manutenzione & Flooring Sagl",
        "uid": "CHE-100.200.410",
        "dedupeKey": "CHE-100.200.410",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200410",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Manutenzione & Flooring Sagl (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c32",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Skalins Arvids, AV Flooring and Maintenance",
        "uid": "CHE-100.200.411",
        "dedupeKey": "CHE-100.200.411",
        "legalForm": "Einzelunternehmen",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200411",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Skalins Arvids, AV Flooring and Maintenance (Einzelunternehmen) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c33",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Helvetia Flooring GmbH",
        "uid": "CHE-100.200.412",
        "dedupeKey": "CHE-100.200.412",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200412",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Helvetia Flooring GmbH (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c34",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Rüedu's Flooring Solutions GmbH",
        "uid": "CHE-100.200.413",
        "dedupeKey": "CHE-100.200.413",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200413",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Rüedu's Flooring Solutions GmbH (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c35",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "TPL FLOORING SA",
        "uid": "CHE-100.200.414",
        "dedupeKey": "CHE-100.200.414",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200414",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "TPL FLOORING SA (AG) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c36",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Wendelmann Flooring Products Schweiz AG",
        "uid": "CHE-100.200.415",
        "dedupeKey": "CHE-100.200.415",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200415",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Wendelmann Flooring Products Schweiz AG (AG) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c37",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Holz & Boden Forum of Flooring GmbH",
        "uid": "CHE-100.200.416",
        "dedupeKey": "CHE-100.200.416",
        "legalForm": "GmbH",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200416",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Holz & Boden Forum of Flooring GmbH (GmbH) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c38",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Zugersee Inter Flooring AG",
        "uid": "CHE-100.200.417",
        "dedupeKey": "CHE-100.200.417",
        "legalForm": "AG",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200417",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Zugersee Inter Flooring AG (AG) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (flooring)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c39",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "ABC All About Bikes KLG",
        "uid": "CHE-100.200.418",
        "dedupeKey": "CHE-100.200.418",
        "legalForm": "Kollektivgesellschaft",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200418",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "ABC All About Bikes KLG (Kollektivgesellschaft) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (about)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c3a",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "About Matcha & Coffee, Inh. Ferreira Antunes",
        "uid": "CHE-100.200.419",
        "dedupeKey": "CHE-100.200.419",
        "legalForm": "Einzelunternehmen",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200419",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "About Matcha & Coffee, Inh. Ferreira Antunes (Einzelunternehmen) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (about)",
        "status": "scored"
    },
    {
        "id": "6a605206b57d7c4ac8a79c3b",
        "campaign": "6a6051bc3512dbe4f4adf7f4",
        "companyName": "Aboutaleb Commerces",
        "uid": "CHE-100.200.420",
        "dedupeKey": "CHE-100.200.420",
        "legalForm": "Einzelunternehmen",
        "registerUrl": "https://www.zefix.ch/en/search/entity/list/firm/100200420",
        "emails": [],
        "phones": [],
        "languages": [],
        "summary": "Aboutaleb Commerces (Einzelunternehmen) based in Switzerland appears to offer general services.",
        "services": [],
        "score": 30,
        "scoreReason": "relevant services (about)",
        "status": "scored"
    }
];
